---
language: python
cache:
  apt: true
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/venv

matrix:
  include:
    - os: linux
      sudo: false
      python: "2.7"
    - os: osx
      sudo: true
      language: generic

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python2 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python2; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  # Install ansible
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install ansible; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install ansible; fi

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
