---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  - mkdir -p $HOME/.ansible/roles/galaxy

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=$HOME/.ansible/roles/galaxy' > $HOME/.ansible.cfg

  - ansible-galaxy install opsroll.ansible
  
    # use opsroll.ansible to setup our ansible conifguration.
  - ansible-playbook tests/setup.yml

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
