---

- name: Install RVM gpg key
  shell: >
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Set RVM auto-reload with message
  lineinfile: >
    dest=$HOME/.rvmrc
    regexp=^rvm_auto_reload=
    line=rvm_auto_reload=1

- name: Install RVM default
  shell: >
    \curl -sSL https://get.rvm.io | bash -s {{opsroll.rvm.default_ruby}}
  notify:
    - reload environment

- name: Install Rubies
  shell: >
    rvm install ruby-{{item}}
  with_items: "{{ opsroll.rvm.rubies }}"
